### ISSUE TITLE
Dynamic Add/Remove

### ISSUE THREAD

**Issue by veragreen119** [bambrikii/leaflet-layer-tree-plugin#10]
This looks like a fantastic plugin but if your leaflet map is using ajax to pull any data then this plugin can't be used because it does not support dynamic adding/removing of layers.  The reason this is important is that with ajax the layer may take a while to load, if for example you are live loading from PstgreSQL and the layer may therefore not exist at the time that the layer tree is initiated. It would be great if this could be added.

**Comment by bambrikii** [comment]
now layers can be added dynamically,
the next version is 2.0.1,
npmjs artifact https://www.npmjs.com/package/leaflet-layer-tree-plugin ,
please see README.md for more details: https://github.com/bambrikii/leaflet-layer-tree-plugin#dynamic-definition-of-layers-code-example .

Thank you.
