### ISSUE TITLE
Broken Links for Usage and Preview

### ISSUE THREAD

**Issue by veragreen119** [bambrikii/leaflet-layer-tree-plugin#12]
Your links to Preview do not work but your demo from the leaflet home page does.  This is the functioning link:
https://rawgit.com/bambrikii/leaflet-layer-tree-plugin/master/examples/basic-example.htm

This is the broken link:
https://htmlpreview.github.io/?https://github.com/bambrikii/leaflet-layer-tree-plugin/blob/master/examples/basic-example.htm

**Comment by bambrikii** [comment]
that's fixed. thanks a lot. the link http://rawgit.com/bambrikii/leaflet-layer-tree-plugin/master/examples/basic-example.htm stopped working some time before, so had to switch to htmlpreview.gitub.io. now it works again.
