### ISSUE TITLE
How add a layer programmatically?

### ISSUE THREAD

**Issue by MappingSteve** [bambrikii/leaflet-layer-tree-plugin#15]
I can't determine from the "basic example" how to add layers that are NOT described in the JS tree object.

I simply want to create "Overlays", then add some nested layer groups and layers, where those elements are previously created in JS code.

Ideally, it would be as simple as:

    let marker = L.marker([lat, lng]);
    let treeLayer1 = {
        name: "Dummy",
        layer: marker
    };
    let tree = {
        code: "overlays",
        name: "Overlays",
        active: true,
        selectedByDefault: false,
        openByDefault: true,
        childLayers: [treeLayer1] };
    new L.Control.LayerTreeControl({
        layerTree: tree,
        openByDefault: true,
    }).addTo(map);

The question is how to correctly define "treeLayer1", given an existing leaflet layer, e.g. "marker".

-----------------------------------------------
Looking at plug-in's source code, this might be as simple as having "traverseLeaf" look for a "layer" property, that is expected to contain a leaflet layer.  
I would try to make that change, but I am unsure what to do with that leaflet layer.

**Comment by bambrikii** [comment]
now layers can be added dynamically,
the next version is 2.0.1,
npmjs artifact https://www.npmjs.com/package/leaflet-layer-tree-plugin ,
please see README.md for more details: https://github.com/bambrikii/leaflet-layer-tree-plugin#dynamic-definition-of-layers-code-example .

Thank you.
