### ISSUE TITLE
Switching layers using javascript

### ISSUE THREAD

**Issue by wambacher** [bambrikii/leaflet-layer-tree-plugin#19]
Hi,

i would like to save the current layer settings (which layers are switched on?) and later enable them again by js.
Saving is not a big problem but how can i enable some layers later?

Background: in my current map (without your layerswitcher) i'll save the layersettings using cookies. Next time the user is using this map, i'll restore the old layer settings.

see: https://wambachers-osm.website/Emergency.html

**Comment by wambacher** [comment]
Found the solution by myself. Using dynamic layers will do it.

**Comment by bambrikii** [comment]
yes, add/remove operations should work. https://github.com/bambrikii/leaflet-layer-tree-plugin#dynamic-definition-of-layers-code-example. was requested some time ago
