### ISSUE TITLE
leaflet 1.x

### ISSUE THREAD

**Issue by wambacher** [bambrikii/leaflet-layer-tree-plugin#5]
does this plugin run with leaflet 1.x? 
tried with 1.2.0 (1.3.x would be better), but 
the basic example does not work for me.

**Comment by bambrikii** [comment]
thanks a lot. after the Leaflet links upgrade to 1.3.2 in basic example, finally have it working.

**Comment by wambacher** [comment]
switched to the - very new - 1.3.3 and the errors have gone :)
Thanks.
