### ISSUE TITLE
are events supported?

### ISSUE THREAD

**Issue by wambacher** [bambrikii/leaflet-layer-tree-plugin#7]
hi,
my old map is working with evens (baselayerchange, overlayadd, overlayremove)
Is there any way to do this using your plugin?

i tryed but without success :(

**Comment by bambrikii** [comment]
currently the plugin extends L.Control (not L.Control.Layers) and does not support "baselayerchange", "overlayadd", "overlayremove".
instead the "layeradd", "layerremove" can be used to handle added/removed layers:
```
	map.on('layeradd', function (a) {
		console.log("layeradd: " + a);
	});
	map.on('layerremove', function (a) {
		console.log("layerremove: " + a);
	});
```
